package reddit_bot.entity;
// Generated 27-ago-2016 1.54.44 by Hibernate Tools 4.3.2-SNAPSHOT


import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Link generated by hbm2java
 */
@Entity
@Table(name="links")
public class Link implements java.io.Serializable {


    private int id;
    private Feed feed;
    private String title;
    private String url;
    private Date publicationDate;
    private Set<LinkSending> linkSendings = new HashSet<LinkSending>(0);

    public Link() {
    }


    public Link(int id, String title, String url, Date publicationDate) {
        this.id = id;
        this.title = title;
        this.url = url;
        this.publicationDate = publicationDate;
    }
    public Link(int id, Feed feed, String title, String url, Date publicationDate, Set<LinkSending> linkSendings) {
        this.id = id;
        this.feed = feed;
        this.title = title;
        this.url = url;
        this.publicationDate = publicationDate;
        this.linkSendings = linkSendings;
    }

    @Id


    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="feed_id")
    public Feed getFeed() {
        return this.feed;
    }

    public void setFeed(Feed feed) {
        this.feed = feed;
    }


    @Column(name="title", nullable=false, length=256)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }


    @Column(name="url", nullable=false, length=512)
    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="publication_date", nullable=false, length=19)
    public Date getPublicationDate() {
        return this.publicationDate;
    }

    public void setPublicationDate(Date publicationDate) {
        this.publicationDate = publicationDate;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="links")
    public Set<LinkSending> getLinkSendings() {
        return this.linkSendings;
    }

    public void setLinkSendings(Set<LinkSending> linkSendings) {
        this.linkSendings = linkSendings;
    }




}


