package reddit_bot.entity;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Link generated by hbm2java
 */
@Entity
@Table(name="links")
public class Link implements java.io.Serializable {

    @Id
    @Column(name="id", unique=true, nullable=false)
    @GeneratedValue(strategy=GenerationType.TABLE)
    private int id;
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="feed_id")
    private Feed feed;
    @Column(name="title", nullable=false, length=256)
    private String title;
    @Column(name="url", nullable=false, length=512)
    private String url;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="publication_date", nullable=false, length=19)
    private Date publicationDate;
    @OneToMany(fetch=FetchType.LAZY, mappedBy="link")
    private Set<LinkSending> linkSendings = new HashSet<LinkSending>(0);

    public Link() {
    }


    public Link(int id, String title, String url, Date publicationDate) {
        this.id = id;
        this.title = title;
        this.url = url;
        this.publicationDate = publicationDate;
    }
    public Link(int id, Feed feed, String title, String url, Date publicationDate, Set<LinkSending> linkSendings) {
        this.id = id;
        this.feed = feed;
        this.title = title;
        this.url = url;
        this.publicationDate = publicationDate;
        this.linkSendings = linkSendings;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }


    public Feed getFeed() {
        return this.feed;
    }

    public void setFeed(Feed feed) {
        this.feed = feed;
    }



    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }



    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }


    public Date getPublicationDate() {
        return this.publicationDate;
    }

    public void setPublicationDate(Date publicationDate) {
        this.publicationDate = publicationDate;
    }


    public Set<LinkSending> getLinkSendings() {
        return this.linkSendings;
    }

    public void setLinkSendings(Set<LinkSending> linkSendings) {
        this.linkSendings = linkSendings;
    }

    @Override
    public String toString() {
        return "Link{" +
                "id=" + id +
                ", feed=" + feed +
                ", title='" + title + '\'' +
                ", url='" + url + '\'' +
                ", publicationDate=" + publicationDate +
                ", linkSendings=" + linkSendings +
                '}';
    }
}


