package reddit_bot.entity;
// Generated 27-ago-2016 1.54.44 by Hibernate Tools 4.3.2-SNAPSHOT


import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * LinkSending generated by hbm2java
 */
@Entity
@Table(name="link_sending")
public class LinkSending  implements java.io.Serializable {


    private Integer id;
    private Link link;
    private String subreddit;
    private Date sendingDate;
    private String url;

    public LinkSending() {
    }


    public LinkSending(Date sendingDate) {
        this.sendingDate = sendingDate;
    }
    public LinkSending(Link link, String subreddit, Date sendingDate, String url) {
        this.link = link;
        this.subreddit = subreddit;
        this.sendingDate = sendingDate;
        this.url = url;
    }

    @Id @GeneratedValue(strategy=IDENTITY)


    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="link_id")
    public Link getLink() {
        return this.link;
    }

    public void setLink(Link link) {
        this.link = link;
    }


    @Column(name="subreddit", length=256)
    public String getSubreddit() {
        return this.subreddit;
    }

    public void setSubreddit(String subreddit) {
        this.subreddit = subreddit;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="sending_date", nullable=false, length=19)
    public Date getSendingDate() {
        return this.sendingDate;
    }

    public void setSendingDate(Date sendingDate) {
        this.sendingDate = sendingDate;
    }


    @Column(name="url", length=512)
    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }




}


